### ISSUE TITLE
001: Corrections in Administrative Units

### ISSUE THREAD

**Issue by gkahiu** [cb-flts/flts#1]
There are a couple of corrections that need to be made when selecting the relevant authority:
1. Under the type of relevant authority, change type from **Settlement** to **Regional Council**
2. Can the region names be sorted alphabetically?
3. Check the references again because when, for example, I select Omeheke Region then Municipality Council as the type, the name of the relevant authority shows Okakarara and Otavi which are not correct are these refer to town councils.
Most likely this is caused by the references made in the query file for inserting details of the relevant authority.
![QGIS 2 18 14 for STDM  30-Jul-19 8_27_41 AM](https://user-images.githubusercontent.com/3840267/62103096-10569080-b2a4-11e9-8a9e-f498dc338e4a.png)

**Comment by joehene** [comment]
The sorting is alpabetically done and adjusted the name as suggested. Commiting these changes. 

For the region, the mismatch is being created on running the configuration wizard as it creates a sorting method of its own. Is there a way to force sorting by alphabetical order within the configuration. The image shows how the arrangement is on configuration

![conf_region](https://user-images.githubusercontent.com/23359514/62120622-9b4a8180-b2ca-11e9-8e1a-5fa610f72d21.jpg)
