### ISSUE TITLE
cant upload document with same file name gives an error

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#11]
When uploading documents with the same name file, an error occurs so we would suggest maybe when uploading a file its generated with a file name such as; schemenumber_chemename_uploaddate.pdf

**Comment by gkahiu** [comment]
Am not sure whether you have pulled the latest version, but the approach has slightly changed. When you upload a file, it is now cached in a **Temp** folder (under **FLTS**). Then once you finish (run the wizard til the end), the file is moved to the corresponding document type folder and has the same name as the auto-generated scheme number, which is guaranteed to be unique under the given document type. Hence, regardless of the name of the document before uploading, the system will rename it using the scheme number.

Please test and confirm.

**Comment by christophine** [comment]
HI John I didn't pull the latest version will do it now. By the way is
there no notification to let me know when to pull the latest version
because I don't get any.

Regards
Christophine

**Comment by gkahiu** [comment]
Yes, it is possible to be receiving email notifications on new changes made to the repository, just note that they may come multiple of them in a day but you can always check the final commit made the day before.

You can follow [these](https://help.github.com/en/articles/about-email-notifications-for-pushes-to-your-repository) instructions to set up automatic email notifications.

**Comment by christophine** [comment]
Ok Thank you
