### ISSUE TITLE
Failing to pull new update

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#15]
I'm trying to do a git pull but I'm getting this error message
![image](https://user-images.githubusercontent.com/52163423/63834515-c382da00-c975-11e9-9085-a5e76a75bb37.png)

**Comment by joehene** [comment]
@christophine seems like the file listed there _drop_recreate_db.bat_ has been changed. I assume that that is the database port number that was changed. Git works in such a way that it cant merge local changes(in your local machine) and what's in the repository until you first commit your changes. Run *git stash* to stash the local changes then run *git pull* to pull the repository

**Comment by christophine** [comment]
Ok Thank you on it

**Comment by christophine** [comment]
Thank you it worked

**Comment by joehene** [comment]
Welcome
