### ISSUE TITLE
Registration divisions

### ISSUE THREAD

**Issue by velzing** [cb-flts/flts#2]
[RegDiv&AU_CODES_MunicipalityTownVillageRegions.xlsx](https://github.com/cb-flts/flts/files/3460798/RegDiv.AU_CODES_MunicipalityTownVillageRegions.xlsx)

We discussed that the registration divisions should be selected automatically after selecting Region, Type of Relevant Authority and Name of Relevant Authority. The list was already provided to @gkahiu. I also attached it again here.

**Comment by joehene** [comment]
@velzing the registration division values are captured as stated in the excel document and a re filtered based on the combobox selections as shown 
![image](https://user-images.githubusercontent.com/23359514/62491823-a4a98180-b7d5-11e9-949d-779b991fc244.png)

**Comment by velzing** [comment]
@joehene We are almost there now. In case the regional councils where there is still a smaller list of Reg. Division, there should still be the option to select between them.
Example: Regional Council of Kharas: Selection options should be: N, S, T or V.

**Comment by joehene** [comment]
Since the selection is itemized into a list, a combobox would be appropriate.
![image](https://user-images.githubusercontent.com/23359514/62819477-8c7f8c80-bb5e-11e9-88dc-e4793ce2c8a7.png)

**Comment by joehene** [comment]
![image](https://user-images.githubusercontent.com/23359514/62829088-bc7e6c80-bbfe-11e9-8a49-a9ed05707f8b.png)

**Comment by joehene** [comment]
@velzing @christophine  Kindly confirm that the registration division values are correctly shown

**Comment by joehene** [comment]
![image](https://user-images.githubusercontent.com/23359514/63946908-a38b0d80-ca7e-11e9-9c97-a890541a01f5.png)
Extra value R that doesn't exist in the Excel for Karas Region

**Comment by joehene** [comment]
![image](https://user-images.githubusercontent.com/23359514/63947856-5f990800-ca80-11e9-932f-71560f6b1328.png)
Bethanie Village Council option Missing Registration Division value

**Comment by joehene** [comment]
This issue has been fixed [here](https://github.com/cb-flts/flts/commit/957c80e9cf257ee97f9f384bf6cd186c55399f13)
