### ISSUE TITLE
Receiving Error message when uploading xml file

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#21]
I have pulled a new request this morning and updated the database, but when testing I'm getting an error message when I upload the xml file and I cant continue with the lodgement.

![image](https://user-images.githubusercontent.com/52163423/64943343-c33a7800-d86b-11e9-82f2-6f8ccd93171d.png)

**Comment by joehene** [comment]
@christophine Have you tried the alternative. Comma Separated Values (.csv) file?
![image](https://user-images.githubusercontent.com/23359514/64945684-c50b3800-d879-11e9-811e-3dece55b32f2.png)

**Comment by christophine** [comment]
Uhhm ohk let me try that now


Sent from Mail for Windows 10

**Comment by joehene** [comment]
@christophine Try this sample excel and CSV attached. You should have the holders info displayed like this. 
[holders_data.xlsx](https://github.com/cb-flts/flts/files/3615494/holders_data.xlsx)

![image](https://user-images.githubusercontent.com/23359514/64947218-326c9800-d87d-11e9-97ca-7ed6ea0567f0.png)

**Comment by christophine** [comment]
Tried it and I am still getting the same e error

Sent from Mail for Windows 10

**Comment by joehene** [comment]
Kindly share the dataset you are using.

**Comment by christophine** [comment]
Dataset from?

Sent from Mail for Windows 10

**Comment by joehene** [comment]
The actual excel file with holder information that you are using in testing
