### ISSUE TITLE
Master authentication password request

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#3]
![MasterPassword Request](https://user-images.githubusercontent.com/52163423/62374740-e23fad80-b53c-11e9-9fba-dc5d4133bb30.png)
Every time after opening the CB-FLTS application it requests the Master Password (needed for accessing the authentication in QGIS). It should be enough for the user to log in only once with their username and password, not being requested to enter another password.

**Comment by joehene** [comment]
If I get you correctly, does the system ask for a different master password other than the one you had set initially?

**Comment by joehene** [comment]
Setting the QGIS_AUTH _PASSWORD_FILE in the systems variables referring to a file containing the master passord will sort out this issue. 
1. Create a file and save the master password in it as text and save it in a folder, say C:\Users\<USER>\ folder
2. Go to start and search for environmental variables
![image](https://user-images.githubusercontent.com/23359514/62447627-7775b880-b76e-11e9-9321-2d76c5b760c0.png)
3. Select Environmental variables button.

4. Select the New... button and add the properties as shown below where the Variable value refers to the file with which you have saved in the previous step.
![image](https://user-images.githubusercontent.com/23359514/62447842-f539c400-b76e-11e9-93b7-b683d76c8058.png)
5. Click ok on all windows and start QGIS. It will start without always prompting for a password.
![image](https://user-images.githubusercontent.com/23359514/62447480-206fe380-b76e-11e9-9f1c-86f9710aaafd.png)

**Comment by christophine** [comment]
No it doesn't ask for a different master password its just that when logging into the FLTS application the user is prompted to enter the password twice which the second password is the master password.

**Comment by christophine** [comment]
Ok will do that thank you.

**Comment by christophine** [comment]
should the file be saved in the .qgis2 folder

**Comment by joehene** [comment]
You could save it in your users/USERNAME folder.

**Comment by christophine** [comment]
Ok thank you

**Comment by christophine** [comment]
It worked thank you.
