### ISSUE TITLE
Error clicking Next... after uploading list of holders.

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#5]
An error has occurred while executing Python code: 

AttributeError: type object 'DocumentTableWidget' has no attribute 'NOT_UPLOADED' 
Traceback (most recent call last):
  File "C:/Users/erik.velzing/.qgis2/python/plugins\stdm\ui\flts\scheme_lodgement.py", line 336, in on_page_changed
    self._load_scheme_document_types()
  File "C:/Users/erik.velzing/.qgis2/python/plugins\stdm\ui\flts\scheme_lodgement.py", line 447, in _load_scheme_document_types
    self.tbw_documents.add_document_type(doc_type)
  File "C:/Users/erik.velzing/.qgis2/python/plugins\stdm\ui\customcontrols\documents_table_widget.py", line 194, in add_document_type
    doc_info = self._doc_info_cls()
  File "C:/Users/erik.velzing/.qgis2/python/plugins\stdm\ui\customcontrols\documents_table_widget.py", line 73, in __init__
    self.upload_status = DocumentTableWidget.NOT_UPLOADED
AttributeError: type object 'DocumentTableWidget' has no attribute 'NOT_UPLOADED'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, e47a6a5 

Python Path:
C:/PROGRA~1/QGISLA~1.14)/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISLA~1.14)/apps/qgis/./python
C:/Users/erik.velzing/.qgis2/python
C:/Users/erik.velzing/.qgis2/python/plugins
C:/PROGRA~1/QGISLA~1.14)/apps/qgis/./python/plugins
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\bin\python27.zip
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\DLLs
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISLA~1.14)\bin
C:\PROGRA~1\QGISLA~1.14)\apps\Python27
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISLA~1.14)\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/erik.velzing/.qgis2//python
C:\Users\erik.velzing\.qgis2\python\plugins\stdm\third_party
C:\Users\erik.velzing\.qgis2\python\plugins\stdm\third_party\fontTools

**Comment by christophine** [comment]
![Untitled](https://user-images.githubusercontent.com/52163423/62529725-7496c880-b83f-11e9-9998-b5ed3561c50e.png)

**Comment by velzing** [comment]
@gkahiu @joehene same error for me on a separate PC. We can not keep testing with @christophine at this stage.

**Comment by joehene** [comment]
@velzing @christophine Kindly check now if the problem has been fixed by pulling the recent updates. This is how it should look on document upload. 
![image](https://user-images.githubusercontent.com/23359514/62718535-a4e09180-ba0e-11e9-9015-6bad8917e921.png)
