### ISSUE TITLE
Duplicate Certificate numbers

### ISSUE THREAD

**Issue by christophine** [cb-flts/flts#62]
Hi Joseph, I would like to raise an issue concerning the duplicate certificate number when lodging the same scheme , is there a possibility to make the system more flexible by continuing where pit last print with the certificate numbering?

**Comment by jkariukidev** [comment]
Hi. The system cannot produce duplicate numbers as it increments the number from the previously generated one. i.e if it is OSHKTI.0001.2020 then the next successive numver will be OSHKTI.0002.2020. Kindly share a screenshot of the *cb_certificate* table with the duplicate certificate number (if any).
