### ISSUE TITLE
Destination CRS value is not variable

### ISSUE THREAD

**Issue by jkariukidev** [cb-flts/flts#63]
Destination CRS is fixed for all plots in output certificate map
![image](https://user-images.githubusercontent.com/23359514/97682158-1a6bce00-1aa9-11eb-9846-5c080741d3d9.png)

**Comment by jkariukidev** [comment]
@christophine Looking into the issue. Once solved, the change will be pushed and you can perform a git pull.

**Comment by jkariukidev** [comment]
I see the issue is being referenced [here](https://github.com/cb-flts/flts/issues/64).

**Comment by christophine** [comment]
Well noted thank you.
